version: '3.3'

services:
  mysql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    build: .
    environment:
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mysql
      WP_HOME: http://localtest.me:8080
      WP_SITEURL: http://localtest.me:8080/cms
    ports:
      - "8080:80"

volumes:
  db_data:
